photoweb/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('website/', include('website.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views


app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('album/<int:album_id>/', views.album, name='album'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
import os.path

from django.db import models

from .apps import WebsiteConfig


def rename_and_upload(instance, filename) -> str:
    upload_to = os.path.join(WebsiteConfig.name, 'images')
    return os.path.join(upload_to, filename)


class Photo(models.Model):
    image = models.FileField(upload_to=rename_and_upload)
    title = models.CharField(max_length=50, default=None, blank=True, null=True)
    dt_shot = models.DateField(default=None, blank=True, null=True)

    def __str__(self):
        return self.image.name


class Album(models.Model):
    title = models.CharField(max_length=100)
    dt_publish = models.DateField()
    subtitle = models.CharField(max_length=100, default=None, blank=True, null=True)
    description = models.CharField(max_length=100, default=None, blank=True, null=True)

    def __str__(self):
        return self.title


class AlbumPhoto(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.RESTRICT)
    is_ref = models.BooleanField(default=False, null=False)

    def __str__(self):
        return f'{self.album} - {self.photo}'


class Tag(models.Model):
    name = models.CharField(max_length=50, default="Default", blank=False, null=False)

    def __str__(self):
        return self.name


class PhotoTag(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.photo} - {self.tag}'

website/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from .models import AlbumPhoto, PhotoTag
from .resources import KEYS, CONFIG
from .wrappers import AlbumDetail, PhotoDetail


def index(request):
    return render(request, 'website/index.html', {"keys": KEYS})


def portfolio(request):
    album_details = []

    album_photos = AlbumPhoto.objects.select_related('photo', 'album').filter(is_ref=True)
    for ap in album_photos:
        nb_photo: int = AlbumPhoto.objects.filter(album=ap.album).count()
        album_details.append(
            AlbumDetail(
                id=ap.album.id,
                title=ap.album.title,
                dt_publish=ap.album.dt_publish,
                ref_photo=ap.photo.image.url,
                subtitle=ap.album.subtitle,
                description=ap.album.description,
                count=nb_photo,
            )
        )

    paginator = Paginator(album_details, CONFIG["page.portfolio.pagination.size"])
    page_number = request.GET.get('page')

    return render(request, 'website/portfolio.html', {"keys": KEYS, "page_obj": paginator.get_page(page_number)})


def album(request, album_id):
    photo_details = []

    album_photos = AlbumPhoto.objects.select_related('photo', 'album').filter(album=album_id)
    for ap in album_photos:
        photo_tags = PhotoTag.objects.select_related('photo', 'tag').filter(photo=ap.photo)
        tags = ", ".join([str(photo_tag.tag) for photo_tag in photo_tags])
        photo_details.append(
            PhotoDetail(
                id=ap.photo.id,
                url=ap.photo.image.url,
                title=ap.photo.title,
                tags=tags,
                dt_shot=ap.photo.dt_shot,
            )
        )

    return render(
        request, 'website/album.html',
        {"keys": KEYS, "album_title": album_photos[0].album.title, "photo_details": photo_details}
    )

website/templates/website/album.html
<!-- website/album.html -->

{% extends "website/lay/main.html" %}
{% load static %}

{% block content %}

<section class="ftco-section ftco-bread">
    <div class="container">
    <div class="row no-gutters slider-text justify-content-center align-items-center">
        <div class="col-md-8 ftco-animate">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'website:index' %}">{{ keys.nav.menu1 }}</a></span>&nbsp;<span>{{ keys.nav.menu2 }}</span></p>
            <h1 class="bread">{{ album_title }}</h1>
        </div>
    </div>
</div>
</section>

<section class="ftco-section-3">
    <div class="photograhy">
        <div class="row">
            {% for photo_detail in photo_details %}
            <div class="col-md-4 ftco-animate">
                <a href="{{ photo_detail.url }}" class="photography-entry img image-popup d-flex justify-content-start align-items-end" style="background-image: url({{ photo_detail.url }});">
                    <div class="overlay"></div>
                    <div class="text ml-4 mb-4">
                        <h3>{{ photo_detail.title }}</h3>
                        <span class="tag">{{ photo_detail.tags }}</span>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% include "website/inc/footer.html" %}

{% endblock %}

<!-- website/album.html -->

website/templates/website/inc/follow.html
<!-- website/inc/follow.html -->

{% load static %}

<section class="ftco-section instagram">

    <div class="container">

        <div class="row justify-content-center mb-2 pb-3">
            <div class="col-md-7 heading-section heading-section-2 text-center ftco-animate">
                <h2 class="mb-4">{{ keys.follow.header }}</h2>
            </div>
        </div>

        <div class="row no-gutters">
            <div class="col-sm-12 col-md ftco-animate">
                <a href="#" class="insta-img image-popup" style="background-image: url({% static 'photoweb/images/image_1.jpg' %});">
                    <div class="icon d-flex justify-content-center">
                      <span class="icon-instagram align-self-center"></span>
                    </div>
                </a>
            </div>

            <div class="col-sm-12 col-md ftco-animate">
                <a href="#" class="insta-img image-popup" style="background-image: url({% static 'photoweb/images/image_2.jpg' %});">
                    <div class="icon d-flex justify-content-center">
                      <span class="icon-instagram align-self-center"></span>
                    </div>
                </a>
            </div>

            <div class="col-sm-12 col-md ftco-animate">
                <a href="#" class="insta-img image-popup" style="background-image: url({% static 'photoweb/images/image_3.jpg' %});">
                    <div class="icon d-flex justify-content-center">
                      <span class="icon-instagram align-self-center"></span>
                    </div>
                </a>
            </div>

            <div class="col-sm-12 col-md ftco-animate">
                <a href="#" class="insta-img image-popup" style="background-image: url({% static 'photoweb/images/image_4.jpg' %});">
                    <div class="icon d-flex justify-content-center">
                      <span class="icon-instagram align-self-center"></span>
                    </div>
                </a>
            </div>

            <div class="col-sm-12 col-md ftco-animate">
                <a href="#" class="insta-img image-popup" style="background-image: url({% static 'photoweb/images/image_5.jpg' %});">
                    <div class="icon d-flex justify-content-center">
                      <span class="icon-instagram align-self-center"></span>
                    </div>
                </a>
            </div>
        </div>

    </div>

</section>   

<!-- website/inc/follow.html -->

website/templates/website/inc/footer.html
<!-- website/inc/footer.html -->

{% load static %}

<footer class="ftco-footer ftco-bg-dark ftco-section">

    <div class="container px-md-5">

        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">{{ keys.footer.header1 }}</h2>
                    <ul class="list-unstyled photo">
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_1.jpg' %});"></a></li>
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_2.jpg' %});"></a></li>
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_3.jpg' %});"></a></li>
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_4.jpg' %});"></a></li>
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_5.jpg' %});"></a></li>
                        <li><a href="#" class="img" style="background-image: url({% static 'photoweb/images/image_6.jpg' %});"></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">{{ keys.footer.header2 }}</h2>
                    <ul class="list-unstyled categories">
                        <li><a href="#">November 2018 <span>(105)</span></a></li>
                        <li><a href="#">October 2018 <span>(212)</span></a></li>
                        <li><a href="#">September 2018 <span>(150)</span></a></li>
                        <li><a href="#">August 2018 <span>(100)</span></a></li>
                        <li><a href="#">July 2018 <span>(200)</span></a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">{{ keys.footer.header3 }}</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    {{ keys.copyright | safe }}                                
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>

    </div>

</footer>

<!-- website/inc/footer.html -->

website/templates/website/inc/loader.html
<!-- website/inc/loader.html -->

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
    </svg>
</div>

<!-- website/inc/loader.html -->

website/templates/website/inc/meta.html
<!-- website/inc/meta.html -->

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- website/inc/meta.html -->

website/templates/website/inc/nav.html
<!-- website/inc/nav.html -->

{% load static %}
{% load website_tags %}

<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>

<aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
    
    <h1 id="colorlib-logo"><a href="{% url 'website:index' %}"><span class="img" style="background-image: url({% static 'photoweb/images/author.jpg' %});"></span>{{ keys.author.name }}</a></h1>
    
    <nav id="colorlib-main-menu" role="navigation">
        <ul>
            <li class="{% active_page request 'index' %}"><a href="{% url 'website:index' %}">{{ keys.nav.menu1 }}</a></li>
            <li class="{% active_page request 'portfolio' %}"><a href="{% url 'website:portfolio' %}">{{ keys.nav.menu2 }}</a></li>
            <li><a href="#">{{ keys.nav.menu3 }}</a></li>
            <li><a href="#">{{ keys.nav.menu4 }}</a></li>
            <li><a href="#">{{ keys.nav.menu5 }}</a></li>
            <li><a href="#">{{ keys.nav.menu6 }}</a></li>
        </ul>
    </nav>

    <div class="colorlib-footer">
        <h3>{{ keys.nav.menu7 }}</h3>
        <div class="d-flex justify-content-center">
            <form action="#" class="colorlib-subscribe-form">
                <div class="form-group d-flex">
                    <div class="icon"><span class="icon-paper-plane"></span></div>
                  <input type="text" class="form-control" placeholder="Enter Email Address">
                </div>
            </form>
        </div>
    </div>

</aside>

<!-- website/inc/nav.html -->

website/templates/website/inc/script.html
<!-- website/inc/script.html -->

{% load static %}

<script src="{% static 'photoweb/js/jquery.min.js' %}"></script>
<script src="{% static 'photoweb/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'photoweb/js/popper.min.js' %}"></script>
<script src="{% static 'photoweb/js/bootstrap.min.js' %}"></script>
<script src="{% static 'photoweb/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'photoweb/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'photoweb/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'photoweb/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'photoweb/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'photoweb/js/aos.js' %}"></script>
<script src="{% static 'photoweb/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'photoweb/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'photoweb/js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'photoweb/js/google-map.js' %}"></script>
<script src="{% static 'photoweb/js/main.js' %}"></script>

<!-- website/inc/script.html -->

website/templates/website/inc/style.html
<!-- website/inc/style.html -->

{% load static %}

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">

<link rel="stylesheet" href="{% static 'photoweb/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/animate.css' %}">

<link rel="stylesheet" href="{% static 'photoweb/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'photoweb/css/aos.css' %}">

<link rel="stylesheet" href="{% static 'photoweb/css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'photoweb/css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/jquery.timepicker.css' %}">

<link rel="stylesheet" href="{% static 'photoweb/css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'photoweb/css/style.css' %}">

<!-- website/inc/style.html -->

website/templates/website/index.html
<!-- website/index.html -->

{% extends "website/lay/main.html" %}
{% load static %}

{% block content %}

<section class="ftco-section-no-padding bg-light">
    
    <div class="hero-wrap">

        <div class="overlay"></div>
        
        <div class="d-flex align-items-center js-fullheight">            
            <div class="author-image text img d-flex">
                <section class="home-slider js-fullheight owl-carousel">
                    <div class="slider-item js-fullheight" style="background-image: url({% static 'photoweb/images/author.jpg' %});"></div>
                    <div class="slider-item js-fullheight" style="background-image:url({% static 'photoweb/images/author-2.jpg' %});"></div>
                </section>
            </div>

            <div class="author-info text p-3 p-md-5">
                <div class="desc">
                    <span class="subheading">{{ keys.author.greeting }}</span>
                    <h1 class="big-letter">{{ keys.author.name }}</h1>
                    <h1 class="mb-4">{{ keys.author.desc1 | safe }}</h1>
                    <p class="mb-4">{{ keys.author.desc2 }}</p>
                    <h3 class="signature h1">{{ keys.author.name }}</h3>
                    <ul class="ftco-social mt-3">
                      <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                      <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                      <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</section>

{% include "website/inc/follow.html" %}     

{% include "website/inc/footer.html" %}

{% endblock %}

<!-- website/index.html -->

website/templates/website/lay/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <title></title>

    {% include "website/inc/meta.html" %}

    {% include "website/inc/style.html" %}
</head>
<body>
    {% block main %}{% endblock %}

    {% include "website/inc/loader.html" %}

    {% include "website/inc/script.html" %}
</body>
</html>

website/templates/website/lay/main.html
<!-- website/lay/main.html -->

{% extends "website/lay/base.html" %}
{% load static %}

{% block main %}

<div id="colorlib-page">

    {% include "website/inc/nav.html" %}
    
    <div id="colorlib-main">
        {% block content %}{% endblock %}
    </div>
</div>

{% endblock %}

<!-- website/lay/main.html -->

website/templates/website/portfolio.html
<!-- website/portfolio.html -->

{% extends "website/lay/main.html" %}
{% load static %}

{% block content %}

<section class="ftco-section ftco-bread">
    <div class="container">
        <div class="row no-gutters slider-text justify-content-center align-items-center">
            <div class="col-md-8 ftco-animate">
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'website:index' %}">{{ keys.nav.menu1 }}</a></span>&nbsp;<span>{{ keys.nav.menu2 }}</span></p>
                <h1 class="bread">{{ keys.header.menu2_desc }}</h1>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    
    <div class="container">
        
        <div class="row d-flex"> 

            <div class="col-lg-8">
                <div class="row">
                    {% for collection in page_obj %}
                    <div class="col-md-12">
                        <div class="blog-entry ftco-animate d-md-flex">
                            <a href="{% url 'website:album' collection.id %}" class="img img-2" style="background-image: url({{ collection.ref_photo }});"></a>
                            <div class="text text-2 p-4">
                                <h3 class="mb-2"><a href="{% url 'website:album' collection.id %}">{{ collection.title }}</a></h3>
                                <div class="meta-wrap">
                                    <p class="meta">
                                        <span>{{ collection.dt_publish }}</span>
                                        <span>{{ collection.count }} {% if collection.count > 1 %}{{ keys.page.portfolio.collection.count_label2 }}{% else %}{{ keys.page.portfolio.collection.count_label1 }}{% endif %}</span>
                                        <br/>
                                        <span><a href="{% url 'website:album' collection.id %}">{{ collection.subtitle }}</a></span>
                                    </p>
                                </div>
                                <p class="mb-4">{{ collection.description }}</p>
                                <p><a href="{% url 'website:album' collection.id %}" class="btn-custom">{{ keys.page.portfolio.collection.link_label }} <span class="ion-ios-arrow-forward"></span></a></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <div class="row">
                    <div class="col">
                        <div class="block-27">
                            <ul>
                                {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>

                                {% with page_obj.number|add:"-2" as previous_previous_page %}
                                {% if previous_previous_page >= 1 %}
                                <li><a href="?page={{ previous_previous_page }}">{{ previous_previous_page }}</a></li>
                                {% endif %}
                                {% endwith %}

                                <li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                                {% endif %}

                                <li class="active"><span>{{ page_obj.number }}</span></li>

                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>

                                {% with page_obj.number|add:"2" as next_next_page %}
                                {% if next_next_page <= page_obj.paginator.num_pages %}
                                <li><a href="?page={{ next_next_page }}">{{ next_next_page }}</a></li>
                                {% endif %}
                                {% endwith %}

                                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-4 sidebar ftco-animate bg-light">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                
                <div class="sidebar-box ftco-animate">
                    <h3 class="sidebar-heading">Categories</h3>
                    <ul class="categories">
                        <li><a href="#">Fashion <span>(6)</span></a></li>
                        <li><a href="#">Technology <span>(8)</span></a></li>
                        <li><a href="#">Travel <span>(2)</span></a></li>
                        <li><a href="#">Food <span>(2)</span></a></li>
                        <li><a href="#">Photography <span>(7)</span></a></li>
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="sidebar-heading">Popular Articles</h3>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'photoweb/images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Dec. 14, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'photoweb/images/image_2.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Dec. 14, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                  <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'photoweb/images/image_3.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> Dec. 14, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="sidebar-heading">Tag Cloud</h3>
                    <ul class="tagcloud">
                        <a href="#" class="tag-cloud-link">animals</a>
                        <a href="#" class="tag-cloud-link">human</a>
                        <a href="#" class="tag-cloud-link">people</a>
                        <a href="#" class="tag-cloud-link">cat</a>
                        <a href="#" class="tag-cloud-link">dog</a>
                        <a href="#" class="tag-cloud-link">nature</a>
                        <a href="#" class="tag-cloud-link">leaves</a>
                        <a href="#" class="tag-cloud-link">food</a>
                    </ul>
                </div>

                <div class="sidebar-box subs-wrap img" style="background-image: url({% static 'photoweb/images/bg_1.jpg' %});">
                    <div class="overlay"></div>
                    <h3 class="mb-4 sidebar-heading">Newsletter</h3>
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
                    <form action="#" class="subscribe-form">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Email Address">
                          <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit">
                        </div>
                    </form>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="sidebar-heading">Archives</h3>
                    <ul class="categories">
                        <li><a href="#">Decob14 2018 <span>(10)</span></a></li>
                        <li><a href="#">September 2018 <span>(6)</span></a></li>
                        <li><a href="#">August 2018 <span>(8)</span></a></li>
                        <li><a href="#">July 2018 <span>(2)</span></a></li>
                        <li><a href="#">June 2018 <span>(7)</span></a></li>
                        <li><a href="#">May 2018 <span>(5)</span></a></li>
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="sidebar-heading">Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut.</p>
                </div>
            </div>

        </div>

    </div>

</section>

{% include "website/inc/footer.html" %}

{% endblock %}

<!-- website/portfolio.html -->